// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUfoBf1a6O5tn2xUtzmRrMp3_b-165e8',
    appId: '1:743206282054:web:a09c7facb5900b544efb47',
    messagingSenderId: '743206282054',
    projectId: 'cryptasafe',
    authDomain: 'cryptasafe.firebaseapp.com',
    storageBucket: 'cryptasafe.firebasestorage.app',
    measurementId: 'G-8HT7NFHL6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP0HpB8A9uwELQ_p46_qht1YtkIMYQniI',
    appId: '1:743206282054:android:16fbbeebb24321c94efb47',
    messagingSenderId: '743206282054',
    projectId: 'cryptasafe',
    storageBucket: 'cryptasafe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6HQIRJn2XZCkwf6m7XgiU5_BDHCuqH54',
    appId: '1:743206282054:ios:7da3231f910fd1f84efb47',
    messagingSenderId: '743206282054',
    projectId: 'cryptasafe',
    storageBucket: 'cryptasafe.firebasestorage.app',
    iosBundleId: 'com.example.cryptasafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6HQIRJn2XZCkwf6m7XgiU5_BDHCuqH54',
    appId: '1:743206282054:ios:7da3231f910fd1f84efb47',
    messagingSenderId: '743206282054',
    projectId: 'cryptasafe',
    storageBucket: 'cryptasafe.firebasestorage.app',
    iosBundleId: 'com.example.cryptasafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGUfoBf1a6O5tn2xUtzmRrMp3_b-165e8',
    appId: '1:743206282054:web:b9809c02a4b3a9d84efb47',
    messagingSenderId: '743206282054',
    projectId: 'cryptasafe',
    authDomain: 'cryptasafe.firebaseapp.com',
    storageBucket: 'cryptasafe.firebasestorage.app',
    measurementId: 'G-7EVNX19TWP',
  );
}
